apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: imartinez
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html/index2.html
            name: html
            subPath: index2.html
      volumes:
       - name: html
         configMap:
           name: hello-world-configmap
            
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: imartinez
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

