apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: imartinez
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        envFrom:
        - configMapRef:
            name: example-configmap
        ports:
        - containerPort: 80
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo '<html><body>Hello from the postStart handler<body></html>' > /usr/share/nginx/html/index.html"]
        #volumeMounts:
        #- name: html
        #  mountPath: "/usr/share/nginx/html/"
        #  readOnly: true
      #volumes:
      #  - name: html
      #    configMap:
      #      name: hello-world-configmap
      #      # An array of keys from the ConfigMap to create as files
      #      items:
      #      - key: "hello_world"
      #        path: "index.html"
            
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: imartinez
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

